export const pastExams = {
  total: 2,
  exams: [
    {
      id: "quick-exam-1",
      name: "Quick Exam - 1",
      questionsCount: 25,
      isCompleted: true,
      subjects: ["Maths", "Chemistry", "Physics"],
      time: {
        is: "25 min",
        from: "10:40 AM",
        to: "11:05 AM",
        on: "12th Oct, 2022",
      },
      marks: {
        secured: 18.25,
        correct: 22,
        incorrect: 3,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-1",
      name: "Custom Exam - 1",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Chemistry", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-2",
      name: "Custom Exam - 2",
      questionsCount: 55,
      isCompleted: true,
      subjects: ["Maths", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "quick-exam-1",
      name: "Quick Exam - 1",
      questionsCount: 25,
      isCompleted: true,
      subjects: ["Maths", "Chemistry", "Physics"],
      time: {
        is: "25 min",
        from: "10:40 AM",
        to: "11:05 AM",
        on: "12th Oct, 2022",
      },
      marks: {
        secured: 18.25,
        correct: 22,
        incorrect: 3,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-1",
      name: "Custom Exam - 1",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Chemistry", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-2",
      name: "Custom Exam - 2",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Maths", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "quick-exam-1",
      name: "Quick Exam - 1",
      questionsCount: 25,
      isCompleted: true,
      subjects: ["Maths", "Chemistry", "Physics"],
      time: {
        is: "25 min",
        from: "10:40 AM",
        to: "11:05 AM",
        on: "12th Oct, 2022",
      },
      marks: {
        secured: 18.25,
        correct: 22,
        incorrect: 3,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-1",
      name: "Custom Exam - 1",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Chemistry", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-2",
      name: "Custom Exam - 2",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Maths", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "quick-exam-1",
      name: "Quick Exam - 1",
      questionsCount: 25,
      isCompleted: true,
      subjects: ["Maths", "Chemistry", "Physics"],
      time: {
        is: "25 min",
        from: "10:40 AM",
        to: "11:05 AM",
        on: "12th Oct, 2022",
      },
      marks: {
        secured: 18.25,
        correct: 22,
        incorrect: 3,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-1",
      name: "Custom Exam - 1",
      questionsCount: 55,
      isCompleted: true,
      subjects: ["Chemistry", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-2",
      name: "Custom Exam - 2",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Maths", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
    {
      id: "custom-exam-2",
      name: "Custom Exam - 2",
      questionsCount: 55,
      isCompleted: false,
      subjects: ["Maths", "Physics"],
      time: {
        is: "55 min",
        from: "2:00 PM",
        to: "2:55 PM",
        on: "13th Oct, 2022",
      },
      marks: {
        secured: 55,
        correct: 55,
        incorrect: 0,
        skipped: 0,
      },
    },
  ],
};
